POST http://0.0.0.0:8081/api/login
Content-Type: application/json

{
  "username": "docker3",
  "password": "docker2"
}

###
POST http://0.0.0.0:8081/api/register
Content-Type: application/json

{
  "username": "docker3",
  "password": "docker2"
}

###
GET http://0.0.0.0:8081/api/assets/treasure.png
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDkyMzY3ODYsImlzcyI6ImRvY2tlcjMifQ.HFr2yUSKvVTZ8CJHH2bA6RwJfpq22wjvU-QkEl2RiQY

{
  "username": "docker3",
  "password": "docker2"
}

###
POST http://localhost:8081/api/logout
Content-Type: application/json

{
  "username": "docker3",
  "password": "docker2"
}
###

