version: "3.9"

services:
  database:
    image: mongo:latest
    container_name: session-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    restart: always
    volumes:
      - ./mongo/scripts:/docker-entrypoint-initdb.d/
      - ./mongo/home/mongodb:/home/mongodb
    ports:
      - 27017:27017
    networks:
      - default
  
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile.server
    container_name: session-backend
    environment:
    - DB_URL=mongodb://username:password@database:27017/admin
    depends_on: 
    - database
    ports:
    - ${SERVER_PORT-8888}:8888
    networks:
      - default