version: "3.9"

services:
  database:
    image: mongo:latest
    container_name: session-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    networks:
      - default
  
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile.server
    container_name: session-backend
    environment:
    - DB_URL=mongodb://host.internal.docker:27017/sessions
    depends_on: 
    - database
    ports:
    - ${SERVER_PORT-8080}:8080
    networks:
      - default