version: "3.9"

services:
  database:
    image: mongo:latest
    restart: always
    container_name: session-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
  
  backend:
    build: 
      context: ./session-server
      dockerfile: Dockerfile.server
    environment:
    - DB_URL=mongodb://username:password@mongodb
    depends_on: 
    - database
