version: '3.9'

services:
  database:
    image: postgres:14-alpine
    restart: always
    container_name: auth-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=tokens
    ports:
      - ${DBPORT-5432}:5432
    volumes:
     - ./postgres-data:/var/lib/postgresql/data
     - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: token-server
    volumes:
     - ./backend:/app
    ports:
     - ${PORT-8081}:8080
    env_file: ./backend/.env
    depends_on:
      - database
    networks:
      - default
  
    
