version: '3.9'

services:
  database:
    image: postgres:14.1-alpine
    restart: always
    container_name: auth-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=tokens
    ports:
      - 5432:5432
    volumes:
     - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: token-server
    volumes:
     - ./backend:/app
    ports:
     - ${SERVER_PORT-8080}:8080
    environment:
     - SECRET=secretsecretsecret
    depends_on:
      - database
    networks:
      - default
  
    
