GET http://localhost:8080/api/assets/treasure.png
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDk1MzQxNzYsImlhdCI6MTY0OTUzMDU3Niwic3ViIjoicHkifQ.lSHVP56b-BH_9gjoBJnfbiy-IqMFYwZ7XaR-lgB74FQ

###
POST http://localhost:8080/api/logout
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDk1MzM3NjUsImlhdCI6MTY0OTUzMDE2NSwic3ViIjoicHkifQ.dh9cow57qZxLKGv154Q5ibvJTfrEGYG2YeNTAVxEfwA

{
  "username": "py",
  "password": "python1"
}
###
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "username": "py",
  "password": "python1"
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "py",
  "password": "python1"
}

###

GET http://127.0.0.1:8080/docs